"""Добавление поля last_seen в модели User

Revision ID: 039994e21700
Revises: e799849b081e
Create Date: 2021-05-06 00:34:11.113068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039994e21700'
down_revision = 'e799849b081e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###
