"""Добавлена новая модель posts

Revision ID: 1a787f0d8dd8
Revises: c75257d1130c
Create Date: 2021-04-23 00:27:21.477216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a787f0d8dd8'
down_revision = 'c75257d1130c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
