"""Добавление тэгов к новостям, обновление модели Post

Revision ID: 65faffcaa1dc
Revises: 1a787f0d8dd8
Create Date: 2021-04-24 15:46:22.542675

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '65faffcaa1dc'
down_revision = '1a787f0d8dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('posts_to_tags',
                    sa.Column('post_id', sa.Integer(), nullable=True),
                    sa.Column('tag_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_to_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
