"""Добавлено поле status у модели User

Revision ID: 82017f699d70
Revises: 
Create Date: 2021-04-22 19:02:04.218677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82017f699d70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
