"""Добавление поля is_answered в модель FriendshipOffer

Revision ID: b3ed175f432a
Revises: 039994e21700
Create Date: 2021-05-23 19:00:16.666475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ed175f432a'
down_revision = '039994e21700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendship_offers', sa.Column('is_answered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friendship_offers', 'is_answered')
    # ### end Alembic commands ###
