"""Добавление поля с изображением User

Revision ID: c0363748345b
Revises: 65faffcaa1dc
Create Date: 2021-04-25 17:10:33.865716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0363748345b'
down_revision = '65faffcaa1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'img')
    # ### end Alembic commands ###
