"""Добавлены значения по умолчанию у модели User

Revision ID: c75257d1130c
Revises: eacada2dd7db
Create Date: 2021-04-22 19:42:54.686697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75257d1130c'
down_revision = 'eacada2dd7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
