"""Добавлены поля marital_status, education у модели User

Revision ID: eacada2dd7db
Revises: 82017f699d70
Create Date: 2021-04-22 19:39:20.105935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eacada2dd7db'
down_revision = '82017f699d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('education', sa.String(), nullable=True))
    op.add_column('users', sa.Column('marital_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'marital_status')
    op.drop_column('users', 'education')
    # ### end Alembic commands ###
